import type { Metadata } from "next";
import { inter } from "./fonts";
import "./globals.css";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "NextJS Tailwind App",
  description: "Generated by create next app and tailwind",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" className="w-10 h-10 absolute top-3 right-5 transform rotate-180">
  <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6.75h10.5M3.75 12h16.5m-16.5 5.25h10.5" />
      </svg>

      <body className={inter.className}>{children}</body>
      <Footer></Footer>
    </html>
  );
}
